import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Analytics } from "@vercel/analytics/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <title>CHcomix</title>
        <div className="w-40">
          <Link href="/">
            <Image
              src="/CHC.png"
              width={175}
              height={175}
              alt="CHC Logo"
              priority={true}
            />
          </Link>
        </div>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
